version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=web_blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
    - ./postgres--data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      DJANGO_SETTINGS_MODULE: cs300_webblog.config.local
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - migration

  migration:
    build: .
    command: python manage.py migrate
    environment:
      DJANGO_SETTINGS_MODULE: cs300_webblog.config.local
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db

