# Generated by Django 3.1.3 on 2021-01-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='hashtag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
